#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

//Mouse settings
#define MK_KINETIC_SPEED

#define MOUSEKEY_DELAY 0

#define MOUSEKEY_INTERVAL 16

#define MOUSEKEY_MOVE_DELTA 25

#define MOUSEKEY_BASE_SPEED 2500

#define MOUSEKEY_ACCELERATED_SPEED 1500

#define MOUSEKEY_WHEEL_DELAY 0

#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 10

